name: Release App

on:
  release:
    types: [published]

jobs:
  release:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci --ignore-scripts
      - run: npm run postinstall
      - run: npm run prerelease
      - name: Build and publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run release
